name: learn-me-a-haskell
version: 0.1.0.0
github: "Riddarvid/learn-me-a-haskell"
license: BSD3
author: "Riddarvid"
maintainer: "44440210+Riddarvid@users.noreply.github.com"
copyright: "2023 Riddarvid"

extra-source-files:
  - README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/Riddarvid/learn-me-a-haskell#readme>

dependencies:
  - base >= 4.7 && < 5
  - random >= 1.2.1.1
  - bytestring >= 0.11.4.0

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints

library:
  source-dirs: src

executables:
  learn-me-a-haskell-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - learn-me-a-haskell

tests:
  learn-me-a-haskell-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - learn-me-a-haskell
